### ISSUE TITLE
Failed batch statements never get logged

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#11]
Since batch statements are parsed and prepared in BatchMessage.execute(), the operation will be aborted before it gets to AuditQueryHandler.processBatch() in case the operation is invalid.

An example being when a batch statement includes an update on a non-existing table.

**Comment by tobier** [comment]
@eperott is this issue fixed with the referenced pull request?

**Comment by eperott** [comment]
No, #14 fixed similar issue (#10) for single update statements.

But this issue is a special case of that bug to which I still don't have a solution.
